;             This file is part of the ZRDX 0.51OSE project
;                     (C) 1998, Sergey Belyakov
;                     (C) 2026, Viacheslav Komenda

;LXHeader STRUC
LXSign equ 0
LXBOrd equ 2
LXWOrd equ 3
LXFormatLevel equ 4
LXCPUType equ 8
LXOsType equ 10
LXModuleVersion equ 12
LXModuleFlags equ 16
LXModuleNPages equ 20
LXEIPObjectN equ 24
LXEIP equ 28
LXESPObjectN equ 32
LXESP equ 36
LXPageSize equ 40
LXPageOffShift equ 44
LXFixupSize equ 48
LXFixupCHS equ 52
LXLoaderSize equ 56
LXLoaderCHS equ 60
LXObjTblOff equ 64
LXObjN equ 68
LXObjPageTblOff equ 72
LXObjIterPageOff equ 76
LXResTableOff equ 80
LXResTableN equ 84
LXResidTblOff equ 88
%assign LX??? 92
LXModDirectOff equ 96
LXModDirectN equ 100
LXFixPageTblOff equ 104
LXFixRecTblOff equ 108
LXImportModOff equ 112
LXImportModN equ 116
LXImportProcOff equ 120
LXPageCHSOff equ 124
LXDataPagesOff equ 128
LXPreloadPagesN equ 132
LXNonResNameOff equ 136
LXNonResNameLen equ 140
LXNonResNameCHS equ 144
LXAutoDSObjN equ 148
LXDebugOff equ 152
LXDebugLen equ 156
LXInstPreloadN equ 160
LXInstDemandN equ 164
LXHeapSize equ 168
LXStackSize equ 172
LXHeader_size equ 176
;local object table, generated by loader
;ObjExtTableS Struc
LOTBase equ 0
LOTSelector equ 4
LOTRes equ 6 ;reserved for aligment
ObjExtTableS_size equ 8
;ObjTableS Struc
OTSize equ 0
OTReloc equ 4
OTFlags equ 8
OTPage equ 12
OTNPages equ 16
OTReserv equ 20
ObjTableS_size equ 24

        VSegm IEBSS
        DFD LoaderStack, 400
        DFL LoaderStackEnd
        DFB Header, 0C0h

        DFD ObjectsTable
        DFD PageTable
        DFD FixupPageTable
        DFD FixupTable
        DFD DataSize
        DFD MemHandler
        DFD ObjTable
        DFD ObjPageTable
        DFD FixupRecordTable
        DFD ObjectsExtTable
        DFD LinAddress      ;DD Header
;DFD LinAddress1
        DFD NextPageFixup   ;Pointer to fixup for next page - limit for current page
        DFD PageIndex       ;absolute index of current page
        DFD MaxPageIndex    ;page index limit for current object
        DFD HeaderAddress
        DFD TaskSize
        DFD LoaderMemHandle
        DFD PageLoadAddress
        DFD LocalTablePtr
        DFD ObjTablePtr
        DFD SrcBase
        DFD PageCount
        DFD FixPageTablePtr
        DFD NextPagePtr
        EVSeg IEBSS
        SEGM IEData
        LDWord lSavedPSP
       dd 0
;LDWord LoaderCodeMemHandle
;       DD 0
;LDWord ExtenderSel
;       DD 0
DefaultFlatSelectors: times 16 dw 0
        ESEG IEData
        SEGM IEText
;assume ds:nothing, cs:IETextG, ss:LGroup
;assume ds:nothing, cs:IETextG, ss:nothing
DPMICall:
        push ecx
        push edi
        mov ecx, ebx
        shr ebx, 16
        mov edi, esi
        shr esi, 16
        int 31h
        _ifnot jc
          shl ebx, 16
          mov bx, cx
          shl esi, 16
          or si, di   ;this instruction clear CF instead of "mov si, di"
          ;clc
        _endif
        pop edi
        pop ecx
        ret

Loader:

%macro DefLDErr 2
        SEGM IEData
%%m:
        DefLLabel zcat2(%1,EM)
        db %2
        ESEG IEData
%1:
        mov edi, %%m wrt LGROUP
        jmp short DispLDError
%endmacro
%macro DOSINT 0-1
        int 21h
%endmacro
      DefLDErr ErrNoDPMIMemory, 'out of DPMI memory$'
      DefLDErr ErrFile@129, "can't read EXE file$"
      DefLDErr ErrEXE@129, 'bad EXE format$'
      DefLDErr ErrUnsupportedFixup@129, 'unsupported fixup record$'
      DefLDErr ErrAllocSel, "can't allocate selector$"
      DefLDErr ErrLock, "can't lock extender$"
      DefLDErr ErrTransferBuf@129, "can't allocate transfer buffer$"
        SEGM IEData
        LLabel LoadErrMsg
        db 'ZRDX loader error: $'
LoadErrMsg1: db 13, 10, '$'
        ESEG IEData
DispLDError:
        push ss
        pop ds
        mov ah, 9
        mov edx, OffLoadErrMsg
        int 21h
        mov edx, edi
        int 21h
        mov edx, LoadErrMsg1
        int 21h
        mov ax, 4CFFh
        int 21h

LoaderEntry:
        mov edi, esp
        push ss
        pop es
        and dword [es:edi + DC_SP], 0
        mov byte [es:edi + DC_EAX + 1], 4Ah
        mov ax, DGROUP16
        sub eax, 10h
        mov [es:edi + DC_ES], ax
        mov word [es:edi + DC_EBX], MouseRHandlerPSize + 10h
        LBack MemBlock0Size, 2
        pushfd
        pop eax
        mov [es:edi + DC_Flags], ax
        mov bx, 21h
        mov ax, 300h
        int 31h
        mov bx, 0
        LLabel PatchPointTStSz
        mov ax, 100h
        int 31h
        _ifnot jnc
          cmp bx, 100h
          jb ErrTransferBuf@129
          mov ax, 100h
          int 31h
          jc ErrTransferBuf@129
        _endif
        movzx ebx, bx
        shl ebx, 4
        add [OffTransferStack], ebx
        add [OffTransferDTA], ebx
        mov [OffTransferSelector], dx
        mov gs, edx
        mov [OffTransferSegment], ax
        mov dx, OffDefaultDTA
        mov ah, 1Ah
        int 21h

        ;int 3

        ;---- setup exception handlers -------
        mov ecx, ebp                ;extender code selector
        mov dx, OffExc3Handler
        mov bl, 3
        mov ax, 203h
        int 31h
        mov dx, OffExc0handler
        mov bl, 0
        mov ax, 203h
        int 31h
        mov dx, ExceptionHandler
        mov di, 10111111b
        _do
          shr edi, 1
          _ifnot jc
            mov ax, 203h
            int 31h
            add edx, 4
          _endif
          inc ebx
          cmp bl, 16
        _enddo jb
        push ds
        push fs
        pop ds
        pop fs
%ifndef Release
        ;jmp $
%endif
LoaderDbgEntry:
        mov ebp, OffHeader
        push ss
        push ebp
        push 0
        push 040h                 ; size of Header
        call FileRead             ;read LE header to IEBSS
        cmp al, 040h
        jne ErrFile@129
        mov eax, [ebp + 3Ch]
;HeaderBase EQU ss:[ebp]
        mov [ss:FileDisp], eax
        push ss
        push ebp
        push 0
        push 0C0h  ; size Header
        call FileRead             ;read LE header to IEBSS
        cmp al, 0C0h
        jne ErrFile@129
        cmp word [ebp], 'LE'
        jne ErrEXE@129
        imul ebx, [ebp + LXObjN], ObjTableS_size
        push ebx                      ;calculate size of internal object table
        mov ax, 501h
        call DPMICall            ;allocate space for object table;
        jc ErrNoDPMIMemory
        pop edx
        ;ca
        push ds ;ss:lFlatSelector
        push ebx
        push dword [ebp + LXObjTblOff]
        push edx
        call FileRead            ;read object table from file
        cmp eax, edx
        jne ErrFile@129
        ;call XX
        mov ecx, [ebp + LXObjN]
        xor edi, edi
        mov edx, edi
;calculates the total memory size for the task and the uninitialized tail, which
;can be occupied
;edx - total length
;esi - uninitialized tail
        _do
          mov eax, [ebx + OTSize]
          add eax, 4095
          shr eax, 12                ;object length in pages
          cmp dword [ebx + OTNPages], 0      ;the object has no initialized pages
                                      ;and its memory can be occupied entirely ?
          _ifnot je
            mov edi, [ebx + OTNPages]
            neg edi
          _endif
          add edi, eax
          add edx, eax
          add ebx, ObjTableS_size
        _enddo loop
        shl edx, 12                 ;convert size in pages to bytes
        mov [ss:OffTaskSize], edx        ;save it for future use

        mov ebx, edx
        mov ax, 503h

        call DPMICall             ;reallocate all memory for application
        jc ErrNoDPMIMemory
        mov [fs:OffImageBaseAddr], ebx ;save it linear address for future
        push ebx

        ;--------------clear all memory------------------
        mov edi, ebx
        mov ecx, [ss:OffTaskSize]
        shr ecx, 2
        xor eax, eax
        push es
        push ds
        pop es
        rep stosd
        pop es
        mov ebx, [ebp + LXObjN]
        mov edi, [ebp + LXFixPageTblOff]
        add edi, [ebp + LXFixupSize]
        lea ebx, [edi + ebx*8]         ;loader + local ot
        mov ax, 501h
        call DPMICall                 ;allocate memory for header
        jc ErrNoDPMIMemory
        mov [ss:OffLoaderMemHandle], esi  ;save handle for free
        mov [ss:OffObjTablePtr], ebx      ;object table shall be first
        push ds ;ss:lFlatSelector
        push ebx
        push dword [ebp + LXObjTblOff]
        xchg eax, edi                ;loader size -> eax
        push eax
        add eax, ebx
        mov [ss:OffLocalTablePtr], eax
        sub ebx, [ebp + LXObjTblOff]
        mov [ss:OffHeaderAddress], ebx  ;virtual address of header start in memory
        call FileRead               ;read loader
%define _relocreg esi
        pop _relocreg     ;fs:ImageBaseAddr
        push -(1)       ;ObjectIndex
        _do jmp
          push eax
%define _pagetblreg edx
%define _objectptrreg eax
%define _pageloadaddress edi
          mov edx, [ss:OffLocalTablePtr]
          mov dword [edx + eax*8 + LOTBase], _relocreg
          mov word [edx + eax*8 + LOTSelector], 0  ;selector is undefined
          mov _pageloadaddress, _relocreg ;address to object load
          imul eax, ObjTableS_size
          add eax, [ebp + LXObjTblOff]
          add eax, [ss:OffHeaderAddress]
          mov edx, [eax + OTSize]    ;load full object size
          add edx, 0FFFh           ;align it on page boundary
          and dx, 0F000h
          add _relocreg, edx
          mov ecx, [eax + OTNPages] ;number of initialized pages in file
          mov _pagetblreg, dword [eax + OTPage]
          dec _pagetblreg
          shl _pagetblreg, 2
          add _pagetblreg, dword [ebp + LXObjPageTblOff]
          add _pagetblreg, dword [ss:OffHeaderAddress]
          _ifnot jecxz
          _do
            movzx eax, byte [edx + 2]
            mov ah, [edx + 1]
            mov ebx, 1000h
            cmp eax, [ebp + LXModuleNPages]
            _ifnot jne
              movzx ebx, word [ebp + LXPageOffShift]
              dec ebx
              and ebx, 0FFFh
              inc ebx
            _endif
            dec eax
            js ErrEXE@129 ;XXX
            shl eax, 12
            add eax, [ebp + LXDataPagesOff]
            push _pageloadaddress
            add _pageloadaddress, 1000h
            push eax
            push ebx
            call PreRead
            add _pagetblreg, 4
          _enddo loop
          _endif
        _while
          pop eax
          inc eax
          cmp eax, [ebp + LXObjN]
        _loop jb
        _enddo
        call ReadFlush
;ProceedFixups PROC

%define _basetablereg ebx
%define _fixupptrreg esi
;FixupEnd
%define _flagsreg eax
%define _flagswreg ax
%define _flagsloreg al
%define _flagshireg ah
%define _objindexreg edx
%define _objindexhireg dh
%define _srcoffreg ecx
%define _srctagreg eax
%define _srctagwreg ax
%define _srctagbreg al
%define _fixjmpreg edi

        ;Proceed fixups
        ;mov edx, offset LGroup:FixMsg
        ;DOSMSG
        mov _basetablereg, dword [ss:OffLocalTablePtr]
        xor _objindexreg, _objindexreg
;Prepare to object loop
        _do
          cmp _objindexreg, dword [ebp + LXObjN] ;all objects complete ?
          _break jae, near                           ;break if yes
          ;mov  eax, [@@ObjIndexReg*8+@@BaseTableReg].LOTBase
          ;mov  ss:SrcBase, eax               ;save linear address of current object
          push _objindexreg
          push dword [ebx + (_objindexreg * 8) + LOTBase]    ;SrcBase
%assign F 0
          imul _objindexreg, ObjTableS_size
          add _objindexreg, dword [ss:OffObjTablePtr]
          mov eax, [edx + OTNPages]
          inc eax
          push eax
          ;mov  ss:PageCount, eax
          mov eax, [edx + OTPage]
          dec eax
          shl eax, 2
          add eax, [ebp + LXFixPageTblOff]
          add eax, [ss:OffHeaderAddress]
          ;mov  ss:FixPageTablePtr, eax
          ;push eax
          _do jmp
    ;Prepare to page loop
            ;mov  eax, ss:FixPageTablePtr
            push _fixupptrreg    ;PageCount
            push eax              ;FixPageTablePtr
%assign F F + 8
            mov _fixupptrreg, [eax]
            mov _srcoffreg, dword [ss:OffHeaderAddress]
            add _srcoffreg, dword [ebp + LXFixRecTblOff]
            add _fixupptrreg, _srcoffreg
            mov eax, [eax + 4]
            add eax, _srcoffreg
            ;mov  ss:NextPagePtr, eax
            push eax
%assign F F + 4
            _do
BeginFixup:
            cmp _fixupptrreg, [esp] ; ss:NextPagePtr
            _break jae    ;  @@ToNextPage
            mov _flagswreg, word [esi]
            test _flagshireg, 3             ;fixup type must be 0
            jne ErrUnsupportedFixup@129
            test _flagsloreg, 20h           ;Source list not supported
            jne ErrUnsupportedFixup@129
            movsx _srcoffreg, word [esi + 2] ;get offset of source
            add _srcoffreg, [esp + F] ;SrcBase
                                          ;calc linear address of source
            movzx _objindexreg, byte [esi + 4]
            test _flagshireg, 40h     ;Object index is 16 bit or 8 ?
            _ifnot jz
              mov _objindexhireg, byte [esi + 5]
              inc _fixupptrreg
            _endif
            dec _objindexreg
                    ;eax - Obj Index
            mov _fixjmpreg, _flagsreg
            and _fixjmpreg, 0Fh
            cmp _fixjmpreg, 2
            je near FixSeg
            test _flagshireg, 10h     ;Target offset is 32 bit ?
            _ifnot jz
            mov _srctagreg, dword [esi + 5]
            add _fixupptrreg, 9
            jmp [ss:FixJmpTable + (_fixjmpreg * 4)]
            _endif
            movzx _srctagreg, word [esi + 5]
            add _fixupptrreg, 7
            jmp [ss:FixJmpTable + (_fixjmpreg * 4)]
            _enddo
            pop eax            ;drop next_page_ptr
%assign F F - 4
    ;To Next Page Increments
            add dword [esp + F], 1000h  ;Update src_base for next page
            ;add  ss:FixPageTablePtr, 4
            pop eax
            add eax, 4     ;FixPageTablePtr
            _while
            pop _fixupptrreg
            dec _fixupptrreg           ;PageCount

          _enddo JNE
  ;To next object increments
          pop _objindexreg               ;drop SrcBase
          pop _objindexreg
          inc _objindexreg
        _enddo Jmp
        ;End Fixup loops

        mov ebx, [ss:OffFileHandle]       ;close EXE file
        mov ah, 3Eh
        DOSINT
        mov edx, [ss:OffLocalTablePtr]
        mov eax, [ebp + LXESPObjectN]
        dec eax
        call CreateSelector1
        mov eax, [eax*8 + edx + LOTBase]
        add eax, [ebp + LXESP]
        push ebx
        push eax
        mov eax, [ebp + LXEIPObjectN]
        dec eax
        call CreateSelector1
        lss esp, [esp]
        push ebx                     ;cs
        mov eax, [eax*8 + edx + LOTBase]
        add eax, [es:OffHeader + LXEIP]
        push eax
        mov ax, 502h    ;free memory
        mov esi, [es:OffLoaderMemHandle]
        call DPMICall
        mov edi, 0
        LBack LoaderCodeMemHandle, 4
        shld esi, edi, 16
        push 0FFFFh
        LBack ExtenderSel, 4
        push OffStarter
        mov es, [es:OfflSavedPSP]
        mov ax, 502h
        xor ebx, ebx
        mov ecx, ebx
        mov edx, ebx
        mov ebp, ebx
        mov fs, bx
        push ss
        pop ds
        retf

CreateSelector01:
        call CreateSelForObject
        jz ErrAllocSel
CreateSelector1:
        movzx ebx, word [eax*8 + edx + LOTSelector]
        or ebx, ebx
        jz CreateSelector01
        ret

        SEGM IEData
FixJmpTable: dd Fix8 ;0
            dd ErrUnsupportedFixup@129 ;1
            dd FixSeg ;2
            dd Fix1616 ;3
            dd ErrUnsupportedFixup@129 ;4
            dd Fix16 ;5
            dd Fix48 ;6
            dd Fix32 ;7
            dd Fix32SR ;8
            times 7 dd ErrUnsupportedFixup@129 ;9-15
        ESEG IEData
Fix8:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        mov byte [ecx], _srctagbreg
        jmp BeginFixup
Fix16:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        mov word [ecx], _srctagwreg
        jmp BeginFixup
Fix48:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        mov [ecx], _srctagreg
        add _srcoffreg, 4
        jmp FixSeg1
Fix1616:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        mov [ecx], _srctagwreg
        inc _srcoffreg
        inc _srcoffreg
        jmp FixSeg1
Fix32:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        mov dword [ecx], _srctagreg
        jmp BeginFixup
Fix32SR:
        add _srctagreg, dword [ebx + (_objindexreg * 8) + LOTBase]
        sub _srctagreg, _srcoffreg
        sub _srctagreg, 4
        mov dword [ecx], _srctagreg
        jmp BeginFixup
FixSeg:
        add _fixupptrreg, 5
FixSeg1:
        movzx _srctagreg, word [ebx + (_objindexreg * 8) + LOTSelector]
        or _srctagreg, _srctagreg
        _ifnot jnz
        mov eax, _objindexreg
        call CreateSelForObject
        ;XXX need Error handler!!
        jmp FixSeg1
        _endif
        mov [ecx], _srctagwreg
        jmp BeginFixup

;ENDP


        SEGM IEData
ReadPos: dd 0 ;size Header
ReadPos0: dd 0
ReadMPos: dd 0 ; size Header+offset LGroup:Header
;BufferOffset dd Header
FileDisp: dd 0 ; 60928   ;length of the stub
%ifndef Release
;DumpHandle DD 0
DumpName: db 'dump.bin', 0
%endif

        LDWord FileHandle
             dd 0
        ESEG IEData
FileRead:
         push ebx
         push ecx
         push edx
;@@MemSel  EQU DWORD PTR ss:[esp+12].16
;@@MemPtr  EQU DWORD PTR ss:[esp+12].12
;@@FilePtr EQU DWORD PTR SS:[esp+12].8
;@@Size    EQU DWORD PTR SS:[esp+12].4
         mov edx, [esp + 12 + 8]
         add edx, [ss:FileDisp]
         mov ecx, edx
         shr ecx, 16
         mov ebx, [ss:OffFileHandle]
         mov ax, 4200h
         ;call XX
         DOSINT 42
         ;int  21h
         _ifnot jc
         ;call EnableTrace
         push ds
         lds edx, [esp + 12 + 12 + 4]
         mov ecx, [esp + 12 + 4 + 4]
         mov ah, 3Fh
         DOSINT
         ;push eax       ;write dump
         ;mov ebx, DumpHandle
         ;mov ah, 40h
         ;DOSINT
         ;pop eax
         pop ds
         ;call DisableTrace
        ;push ecx
        ;push 8
        ;call PrintN
        ;push eax
        ;push 8
        ;call PrintN
         _endif
         pop edx
         pop ecx
         pop ebx
         ret 16

ReadFlush:
        mov edx, [ss:ReadPos0]
        cmp edx, [ss:ReadPos]
        _ifnot je
        mov ecx, edx
        shr ecx, 16
        mov ebx, [ss:OffFileHandle]
        mov ax, 4200h
        DOSINT 42
        jc SeekErr@133
        mov ecx, [ss:ReadPos]
        sub ecx, [ss:ReadPos0]
        add [ss:ReadPos0], ecx
        mov edx, [ss:ReadMPos]
        sub edx, ecx
        mov ah, 3Fh
        DOSINT
        _endif
SeekErr@133:
        ret


PreRead:
        push eax
        push ebx
        push ecx
        push edx
;@@MPos EQU DWORD PTR ss:[esp+16].12
;@@FPos EQU DWORD PTR ss:[esp+16].8
;@@Size EQU DWORD PTR ss:[esp+16].4
        mov eax, [esp + 16 + 8]
        cmp eax, [ss:ReadPos]
        jne ReadLast@135
        mov edx, [esp + 16 + 12]
        cmp edx, [ss:ReadMPos]
        je ret@135
ReadLast@135:
        call ReadFlush
        mov eax, [esp + 16 + 8]
        mov [ss:ReadPos0], eax
        mov edx, [esp + 16 + 12]
ret@135:
        add eax, [esp + 16 + 4]
        add edx, [esp + 16 + 4]
        mov [ss:ReadPos], eax
        mov [ss:ReadMPos], edx
        pop edx
        pop ecx
        pop ebx
        pop eax
        ret 12

;NOWARN RES
;DGROUP group STACK

;create a selector for the object by the object index
;if the object is 16-bit then base = object base, limit = object length
;otherwise base = 0, limit = 4G

;ebx-base, ecx-size, dx-attrs
;return selector in ebx
;ax destroyed
CreateSelector:
               push edi
               sub esp, 8        ;alloc space for descriptor
;Cache EQU ss:[esp]
               cmp ecx, 100000h  ;may use byte limit ?
               _ifnot jb
               or dh, 80h
               add ecx, 0FFFh
               shr ecx, 12
               _endif
               mov ax, cs
               and eax, 3
               shl eax, 5         ;setup privelegy level
               or dl, al
               or dl, 1
               mov [esp], ecx
               shr ecx, 16
               or dh, cl
               mov [esp + 2], ebx
               shr ebx, 24
               mov [esp + 7], bl
               mov [esp + 5], dx
               mov cx, 1
               xor eax, eax
               int 31h
               jc ErrAllocSel
               ;$ifnot jc
               movzx ebx, ax
               mov ax, 0Ch
               mov edi, esp
               push es
               push ss
               pop es
               int 31h
               pop es
               jc ErrAllocSel
               ;$endif
               ;mov ebx, bx
               add esp, 8
               pop edi
               ret

;eax - ObjIndex
CreateSelForObject:
        SEGM IEData
AttrTranslateTable@139: db 0 ;0    all flags zero               ?
                     db 0 ;1    conformed but not executable ?
                     db 90h ;10   readable data
                     db 0 ;11   conformed but not executable ?
                     db 0 ;100  writable but not readable    ?
                     db 0 ;101  conformed but not executable ?
                     db 92h ;110  readable & writable data
                     db 0 ;111  conformed but not executable ?
                     db 98h ;1000 executable only
                     db 9Ch ;1001 conformed executable
                     db 9Ah ;1010 readable & executable
                     db 9Eh ;1011 conformed readable & executable
                     db 0 ;1100 executable but writable ?
                     db 0 ;1101 executable but writable ?
                     db 0 ;1110 executable but writable ?
                     db 0 ;1111 executable but writable ?
        ESEG IEData
               pushad
               mov edi, [ss:OffLocalTablePtr]
               imul esi, eax, ObjTableS_size
               add esi, [ss:OffObjTablePtr]
               mov ecx, [esi + OTFlags]
               mov edx, ecx
               shl ch, 2
               rcl cl, 1
               and ecx, 1111b
               mov dl, [ss:ecx + AttrTranslateTable@139]
               mov ebx, [eax*8 + edi + LOTBase]
               lea edi, [eax*8 + edi + LOTSelector]
               or dl, dl
               jz InvalidFlags@139
               shl dh, 1
               and dh, 40h
               _ifnot jz        ;32bit selector(flat) ?
                 lea esi, [ss:ecx*2 + DefaultFlatSelectors]
                 movzx ebx, word [ss:esi]
                 or ebx, ebx
                 _ifnot jnz           ;all flat segments with same attributes
                   ;xor  ebx, ebx       ;may share one flat selector
                   mov ecx, 0FFFFF000h
                   call CreateSelector
                 _endif
                 mov [ss:esi], bx
               _else jmp
                 mov ecx, [esi + OTSize]
                 call CreateSelector
               _endif
ret@139:
        mov [edi], bx
               popad
               ret
InvalidFlags@139:
        xor ebx, ebx
               stc
               jmp ret@139

%ifndef Release
Print8L:
        push dword [esp + 4]
        push 8
        call PrintNL
        pushad
        mov ax, 0E00h + ' '
        int 10h
        popad
        ret 4

PrintNL:
        push eax
        push ecx
;@@Digit EQU DWORD PTR ss:[esp+8].8
;@@N     EQU DWORD PTR ss:[esp+8].4
        mov eax, [esp + 8 + 8]
        mov cl, 8
        sub cl, [esp + 8 + 4]
        shl cl, 2
        rol eax, cl
        mov ecx, [esp + 8 + 4]
        _do
        rol eax, 4
        pushad
        and al, 1111b
        add al, '0'
        cmp al, '9'
        _ifnot jbe
        add al, 'A' - '9' - 1
        _endif
        mov ah, 0Eh
        mov bx, 07h
        int 10h
        popad
        _enddo loop
        pop ecx
        pop eax
        ret 8

%endif
        ESEG IEText
